ConvertFrom-StringData -StringData @'
	ChkUpdate                 = ソリューション ツールボックス
	UpdateServerSelect        = 自動サーバー選択またはカスタム選択
	UpdateServerNoSelect      = 利用可能なサーバーを選択してください
	UpdateSilent              = アップデートが利用可能な場合、サイレントアップデート
	ForceUpdate               = 強制的に確認して更新する
	UpdateReset               = このソリューションをリセットする
	UpdateResetTips           = ダウンロードアドレスが利用可能になると、自動的にダウンロードして更新するように強制されます。
	UpdateCheckServerStatus   = サーバーのステータスを確認します ( 合計 {0} オプション )
	UpdateServerAddress       = サーバーアドレス: {0}
	UpdateServeravailable     = ステータス: 利用可能
	UpdateServerUnavailable   = ステータス: 利用不可
	UpdatePriority            = 優先的に設定されています
	UpdateServerTestFailed    = 失敗したサーバー ステータス テスト
	UpdateQueryingUpdate      = 更新をクエリしています...
	UpdateQueryingTime        = 最新バージョンが利用可能かどうかを確認すると、接続に {0} ミリ秒かかりました。
	UpdateConnectFailed       = リモート サーバーに接続できません。更新が中止されたことを確認してください。
	UpdateMinimumVersion      = 更新プログラムの最小バージョン要件を満たしている、最小必要バージョン: {0}
	UpdateVerifyAvailable     = アドレスが使用可能であることを確認します
	UpdateDownloadAddress     = ダウンロードリンク:
	UpdateAvailable           = 利用可能
	UpdateUnavailable         = 利用不可
	UpdateCurrent             = 現行版: \
	UpdateLatest              = 利用可能な最新バージョン: \
	UpdateNewLatest           = 利用可能な新しいバージョンを見つけました!
	UpdateSkipUpdateCheck     = 事前構成されたポリシーでは、自動更新を初めて実行することはできません。
	UpdateTimeUsed            = 使用時間:
	UpdatePostProc            = 後処理
	UpdateNotExecuted         = 未実行
	UpdateNoPost              = 後処理タスクが見つかりません
	UpdateUnpacking           = 開梱
	UpdateDone                = 正常に更新されました！
	UpdateDoneRefresh         = 更新が完了したら、関数処理を実行します。
	UpdateUpdateStop          = 更新のダウンロード中にエラーが発生し、更新プロセスが中止されました。
	UpdateInstall             = この更新プログラムをインストールしますか?
	UpdateInstallSel          = はい、上記の更新がインストールされます\nいいえ、更新はインストールされません
	UpdateNoUpdateAvailable   = \n   利用可能なアップデートはありません。\n\n   あなたは走っている {0}'s Solutions の入手可能な最新バージョン。\n
	UpdateNotSatisfied        = \n   アップデートプログラムの最小バージョン要件を満たしていない、\n\n   最低限必要なバージョン: {0}\n\n   もう一度ダウンロードしてください {1}'s Solutions このツールを更新するには。\n\n   チェックの更新が中止されました。\n
'@