ConvertFrom-StringData -StringData @'
	# Main page
	Mainname                  = 해결책
	Mainpage                  = 솔루션 도구 상자
	Update                    = 업데이트 확인
	Reset                     = 초기화
	Disable                   = 비활성화
	Done                      = 수행하다
	OK                        = 결정
	Cancel                    = 취소
	Exit                      = 그만두 다
	AllSel                    = 모두 선택
	AllClear                  = 모두 지우기
	Inoperable                = 작동 불가
	ForceUpdate               = 강제 확인 및 업데이트
	SettingLangAndKeyboard    = 시스템 언어 및 키보드 설정
	SwitchLanguage            = 언어 전환
	RefreshModules            = 모듈 다시로드
	Choose                    = 선택하세요
	FailedCreateFolder        = 디렉터리 생성 실패:
	ToMsg                     = \n   {0} 몇 초 후 자동으로 주 메뉴로 돌아갑니다.
	ToQuit                    = \n   {0} 몇 초 안에 메인 메뉴를 종료합니다.
	PlanTask                  = 예약 된 일정

	NetworkLocationWizard     = 네트워크 위치 마법사
	UseZip                    = {0} 압축 해제 소프트웨어 사용
	UseOSZip                  = 시스템과 함께 제공되는 압축 해제 소프트웨어 사용
	UserCancel                = 사용자가 작업을 취소했습니다.
	SetLang                   = 시스템 기본 언어 설정 :
	KeyboardSequence          = 키보드 시퀀스 :
	Wubi                      = Wubi
	Pinyi                     = 병음

	# update
	UpdateServerSelect        = 자동 서버 선택 또는 사용자 지정 선택
	UpdateServerNoSelect      = 사용 가능한 서버를 선택하십시오
	UpdateSilent              = 사용 가능한 업데이트가있을 때 자동 업데이트
	UpdateReset               = 이 솔루션 재설정
	UpdateResetTips           = 다운로드 주소를 사용할 수 있으면 자동으로 다운로드 및 업데이트해야합니다.
	UpdateExit                = 자동 업데이트 스크립트는 {0} 초 후에 자동으로 종료됩니다.
	UpdateCheckServerStatus   = 서버 상태 확인 ( 총 {0} 선택 사항 )
	UpdateServerAddress       = 서버 주소: {0}
	UpdateServeravailable     = 상태: 사용 가능
	UpdateServerUnavailable   = 상태: 사용할 수 없음
	UpdatePriority            = 우선 순위로 설정 됨
	UpdateServerTestFailed    = 서버 상태 테스트 실패
	UpdateQueryingUpdate      = 업데이트 쿼리 중 ...
	UpdateQueryingTime        = 최신 버전을 사용할 수 있는지 확인하는 데 연결하는 데 {0} 밀리 초가 걸렸습니다.
	UpdateConnectFailed       = 원격 서버에 연결할 수 없습니다. 업데이트가 중단되었는지 확인하십시오.
	UpdateMinimumVersion      = 최소 업데이트 프로그램 버전 요구 사항, 최소 필수 버전을 충족합니다: {0}
	UpdateVerifyAvailable     = 주소를 사용할 수 있는지 확인
	UpdateDownloadAddress     = 다운로드 링크:
	UpdateAvailable           = 유효한
	UpdateUnavailable         = 없는
	UpdateCurrent             = 현재 버전 : \
	UpdateLatest              = 사용 가능한 최신 버전 : \
	UpdateNewLatest           = 사용 가능한 새 버전을 찾았습니다!
	UpdateForce               = 업데이트가 강제 중입니다.
	UpdateSkipUpdateCheck     = 사전 구성된 정책은 처음으로 자동 업데이트 실행을 허용하지 않습니다.
	UpdateTimeUsed            = 사용 시간 :
	UpdatePostProc            = 후 처리
	UpdateNotExecuted         = 실행되지 않음
	UpdateNoPost              = 사후 처리 작업이 없습니다.
	UpdateUnpacking           = 포장 풀기 :
	UpdateDone                = 성공적으로 업데이트되었습니다!
	UpdateUpdateStop          = 업데이트를 다운로드하는 동안 오류가 발생하여 업데이트 프로세스가 중단되었습니다.
	UpdateInstall             = 이 업데이트를 설치 하시겠습니까?
	UpdateInstallSel          = 예, 위 업데이트가 설치됩니다.\n아니요, 업데이트가 설치되지 않습니다.
	UpdateNoUpdateAvailable   = \n   사용 가능한 업데이트가 없습니다.\n\n   {0} 솔루션의 최신 버전을 실행 중입니다.\n
	UpdateNotSatisfied        = \n   최소 업데이트 프로그램 버전 요구 사항을 충족하지 않습니다,\n\n   필요한 최소 버전 : {0}\n\n   다시 다운로드하십시오 {1}'s Solutions 사본, 이 도구를 업데이트합니다.\n\n   업데이트 확인이 중단되었습니다.\n
'@