ConvertFrom-StringData -StringData @'
	FirstDeployment           = 首次体验部署
	FirstDeploymentPopup      = 弹出主界面
	FirstExpFinishOnDemand    = 允许首次预体验，按计划
	SettingLangAndKeyboard    = 设置系统语言和键盘
	SettingUTF8               = Beta 版：使用 Unicode UTF-8 提供全球语言支持
	SettingUTF8Tips           = 使用后也许会引发新问题。
	SettingLocale             = 设置系统区域
	SettingLocaleTips         = 不存在部署区域标记时有效。
	PreAppxCleanup            = Appx 清理维护任务
	CleanupOndemandLP         = 阻止清理未使用的按需功能语言包
	CleanupUnusedLP           = 阻止清理未使用的语言包
	Restricted                = 恢复 Powershell 执行策略：受限
	DiskSearch                = 搜索计划：
	DiskSearchFind            = 搜索到，正在运行中：{0}
	DeployCleanup             = 清理 Deploy 目录
	DeployTask                = 部署任务：
	Reboot                    = 重新启动计算机
	NetworkLocationWizard     = 网络位置向导
	LangMul                   = 多语言
	LangSingle                = 单语
	RandomlyWaitSel           = 等待随机选择的语言
	RandomlySelResults        = 随机选择结果
	LanguageInstalled         = 系统已安装语言包
	SetLang                   = 设置系统首选语言：
	SetTimezone               = 设置时区：
	KeyboardSequence          = 键盘顺序：
	Wubi                      = 五笔
	Pinyi                     = 拼音
'@